version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=temporal
      - MYSQL_DATABASE=temporal
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:1.23.1
    environment:
      - DB=mysql
      - MYSQL_SEEDS=mysql
      - MYSQL_USER=root
      - MYSQL_PWD=temporal
      - MYSQL_DB=temporal
    ports:
      - "7233:7233"
    depends_on:
      mysql:
        condition: service_healthy
    
  temporal-ui:
    image: temporalio/ui:latest
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb+srv://kavin25042003:Kavin%402003@cluster0.7b5gb.mongodb.net/usermanagement
      - NODE_ENV=production
      - AUTH0_CLIENT_ID=dpNlNcUhHplzzCdQsMHopXpRj61v8odJ
      - AUTH0_CLIENT_SECRET=ZIVZ8MszY8AyhwQy6XyXusG8H-3cu3t3ZR0QVHYgtOrq8dFpbM5VV6NLEnDf0i9c
      - GRANT_TYPE=client_credentials
      - AUTH0_DOMAIN=dev-z5htpfd1ttgn2n0d.us.auth0.com
      - GMAIL_APP_PASSWORD=ffxeiygdxlknzwdv
      - GMAIL_USER=kavinraj25042003@gmail.com
    depends_on:
      - temporal

    volumes:
      - ./backend:/app/backend
 
  orgworker:
    build:
      context: ./backend
      dockerfile: temporal/workers/Dockerfile
    depends_on:
      - temporal
    environment:
       
      - DB_URI=mongodb+srv://kavin25042003:Kavin%402003@cluster0.7b5gb.mongodb.net/usermanagement

      - NODE_ENV=production
      - AUTH0_CLIENT_ID=dpNlNcUhHplzzCdQsMHopXpRj61v8odJ
      - AUTH0_CLIENT_SECRET=ZIVZ8MszY8AyhwQy6XyXusG8H-3cu3t3ZR0QVHYgtOrq8dFpbM5VV6NLEnDf0i9c
      - GRANT_TYPE=client_credentials
      - AUTH0_DOMAIN=dev-z5htpfd1ttgn2n0d.us.auth0.com
      - GMAIL_APP_PASSWORD=ffxeiygdxlknzwdv
      - GMAIL_USER=kavinraj25042003@gmail.com
      - TEMPORAL_ADDRESS=temporal:7233
    restart: unless-stopped
    command: npm run start:orgworker
    volumes:
      - ./backend/temporal/workers:/app/backend/temporal/workers

  userworker:
    build:
      context: ./backend
      dockerfile: temporal/workers/Dockerfile
    depends_on:
      - temporal
    
      
    environment:
      - DB_URI=mongodb+srv://kavin25042003:Kavin%402003@cluster0.7b5gb.mongodb.net/usermanagement

      - NODE_ENV=production
      - AUTH0_CLIENT_ID=dpNlNcUhHplzzCdQsMHopXpRj61v8odJ
      - AUTH0_CLIENT_SECRET=ZIVZ8MszY8AyhwQy6XyXusG8H-3cu3t3ZR0QVHYgtOrq8dFpbM5VV6NLEnDf0i9c
      - GRANT_TYPE=client_credentials
      - AUTH0_DOMAIN=dev-z5htpfd1ttgn2n0d.us.auth0.com
      - GMAIL_APP_PASSWORD=ffxeiygdxlknzwdv
      - GMAIL_USER=kavinraj25042003@gmail.com
      - TEMPORAL_ADDRESS=temporal:7233
    restart: unless-stopped
    command: npm run start:userworker
    volumes:
      - ./backend/temporal/workers:/app/backend/temporal/workers

    
    